const objKeywords = [
  "properties",
  "patternProperties",
  "additionalProperties",
  "propertyNames",
  "minProperties",
  "maxProperties",
  "required",
  "unevaluatedProperties",
  "dependencies",
  "dependentRequired",
  "dependentSchemas",
];
const arrKeywords = [
  "items",
  "additionalItems",
  "prefixItems",
  "uniqueItems",
  "contains",
  "minContains",
  "maxContains",
  "minItems",
  "maxItems",
  "unevaluatedItems",
];
const strKeywords = [
  "minLength",
  "maxLength",
  "pattern",
  "contentEncoding",
  "contentMediaType",
  "contentSchema",
];
const numKeywords = [
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "multipleOf",
];

export const incompatibleKeywords = {
  string: [...objKeywords, ...arrKeywords, ...numKeywords],
  number: [...objKeywords, ...arrKeywords, ...strKeywords],
  integer: [...objKeywords, ...arrKeywords, ...strKeywords],
  boolean: [...objKeywords, ...arrKeywords, ...strKeywords, ...numKeywords],
  array: [...objKeywords, ...strKeywords, ...numKeywords],
  object: [...arrKeywords, ...strKeywords, ...numKeywords],
  null: [...objKeywords, ...arrKeywords, ...strKeywords, ...numKeywords],
};
export const baseSchemaKeys: Set<string> = new Set([
  ...objKeywords,
  ...numKeywords,
  ...strKeywords,
  ...arrKeywords,
  "$schema",
  "deprecated",
  "$id",
  "id",
  "type",
  "format",
  "anyOf",
  "allOf",
  "not",
  "oneOf",
  "if",
  "then",
  "elseIf",
  "else",
  "const",
  "enum",
  "title",
  "description",
  "examples",
  "$comment",
  "default",
  "readOnly",
  "writeOnly",
  "$ref",
  "$defs",
  "definitions",
  "__functionName",
  "allFormats",
  "$dynamicAnchor",
  "$dynamicRef",
  "$anchor",
  "$vocabulary",
  "errorMessage",
]);

export const dataKeywords = [
  "minLength",
  "maxLength",
  "pattern",
  "format",
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "multipleOf",
  "minItems",
  "maxItems",
  "uniqueItems",
  "minContains",
  "maxContains",
  "minProperties",
  "maxProperties",
  "required",
  "const",
  "enum",
];

export const keywordValueTypes = {

  minimum: "number",
  maximum: "number",
  exclusiveMinimum: "number",
  exclusiveMaximum: "number",
  multipleOf: "number",

  minLength: "integer",
  maxLength: "integer",
  minItems: "integer",
  maxItems: "integer",
  minProperties: "integer",
  maxProperties: "integer",
  minContains: "integer",
  maxContains: "integer",

  pattern: "string",
  format: "string",

  uniqueItems: "boolean",
  readOnly: "boolean",
  writeOnly: "boolean",

  type: "string | string[]",

  enum: "any[]",
  const: "any",

  additionalProperties: "schema",
  unevaluatedProperties: "schema",
  propertyNames: "schema",
  additionalItems: "schema",
  unevaluatedItems: "schema",
  contains: "schema",
  items: "schema | schema[]",
  not: "schema",
  if: "schema",
  then: "schema",
  else: "schema",

  prefixItems: "schema[]",
  allOf: "schema[]",
  anyOf: "schema[]",
  oneOf: "schema[]",
  elseIf: "{if: schema, then: schema}[]",

  properties: "object",
  patternProperties: "object",
  dependentSchemas: "object",
  dependentRequired: "object",
  dependencies: "object",
  $defs: "object",
  definitions: "object",
  $vocabulary: "object",

  // string arrays
  required: "string[]",
  allFormats: "string[]",

  // identifiers / refs
  $id: "string",
  $schema: "string",
  $ref: "string",
  $dynamicRef: "string",
  $anchor: "string",
  $dynamicAnchor: "string",

  // annotations / misc
  title: "string",
  description: "string",
  examples: "any[]",
  default: "any",
  formatMode: "string",
  errorMessage: "string | object",
} as const;
